title: "Vong Jun Yi"
author: "Vong Jun Yi"
description: "Sunway College Kuala Lumpur"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%d %B %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "resume.md", title: "CV"}
  - {file: "blog.md", title: "Blog"}
  - {file: "notes.md", title: "Notes"}
  - {file: "activities.md", title: "Activities"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:vongjunyi05@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/vongjy"}
  - {title: LinkedIn, icon: linkedin, url: "https://linkedin.com/in/vongjunyi"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
